remote_theme: pmarsceill/just-the-docs
lang: en
title: Stastic Docs
description: Documentation site for Stastic website editor
baseurl: /just-the-docs/
permalink: pretty
exclude:
  - node_modules/
  - '*.gemspec'
  - '*.gem'
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - script/
  - LICENSE.txt
  - lib/
  - bin/
  - README.md
  - Rakefile
search_enabled: true
color_scheme: nil
ga_tracking: null
aux_links:
  Just the Docs on GitHub:
    - //github.com/pmarsceill/just-the-docs
